alphabets = ( 
    (u'А', u'а', u'а [a]', u'/a/', u'father'),	
    (u'Б', u'б', u'бэ [bɛ]', u'/b/ or /bʲ/', u'bit'),
    (u'В', u'в', u'вэ [vɛ]', u'/v/ or /vʲ/', u'vine'),
    (u'Г', u'г', u'гэ [ɡɛ]', u'/ɡ/', u'go'),
    (u'Д', u'д', u'дэ [dɛ]', u'/d/ or /dʲ/', u'do'),
    (u'Е', u'е', u'е [je]', u'/je/ or /ʲe/', u'yet'),
    (u'Ё', u'ё', u'ё [jo]', u'/jo/ or /ʲo/', u'yolk'),
    (u'Ж', u'ж', u'жэ [ʐɛ]', u'/ʐ/', u'pleasure'),
    (u'З', u'з', u'зэ [zɛ]', u'/z/ or /zʲ/', u'zoo'),
    (u'И', u'и', u'и [i]', u'/i/ or /ʲi/', u'me'),
    (u'Й', u'й', u'и краткое [i ˈkratkəɪ]', u'/j/', u'yes'),
    (u'К', u'к', u'ка [ka]', u'/k/ or /kʲ/', u'kitten'),
    (u'Л', u'л', u'эл [el] or эль [elʲ]', u'/l/ or /lʲ/', u'lamp'),
    (u'М', u'м', u'эм [ɛm]', u'/m/ or /mʲ/', u'map'),
    (u'Н', u'н', u'эн [ɛn]', u'/n/ or /nʲ/', u'not'),
    (u'О', u'о', u'o [o]', u'/o/', u'more'),
    (u'П', u'п', u'пэ [pɛ]', u'/p/ or /pʲ/', u'spell'),
    (u'Р', u'р', u'эр [ɛr]', u'/r/ or /rʲ/', u'rolled r'),
    (u'С', u'с', u'эс [ɛs]', u'/s/ or /sʲ/', u'see'),
    (u'Т', u'т', u'тэ [tɛ]', u'/t/ or /tʲ/', u'stool'),
    (u'У', u'у', u'у [u]', u'/u/', u'boot'),
    (u'Ф', u'ф', u'эф [ɛf]', u'/f/ or /fʲ/', u'face'),
    (u'Х', u'х', u'ха [xa]', u'/x/', u'Loch (voiceless velar fricative)'),
    (u'Ц', u'ц', u'це [tsɛ]', u'/t͡s/', u'sits'),
    (u'Ч', u'ч', u'че [tɕe]', u'/t͡ɕ/', u'chip'),
    (u'Ш', u'ш', u'ша [ʂa]', u'/ʂ/', u'Close to shut (voiceless retroflex fricative)'),
    (u'Щ', u'щ', u'ща [ɕɕa]', u'/ɕɕ/', u'sheer (sometimes instead pronounced as with fresh cheese) (a voiceless alveolo-palatal fricative)'),
    (u'Ъ', u'ъ', u'твёрдый знак [ˈtvʲordɨj znak]', u'', u'silent, prevents palatalization of the preceding consonant'),
    (u'Ы', u'ы', u'ы [ɨ]', u'[ɨ]', u'roses or silly (close central unrounded vowel)'),
    (u'Ь', u'ь', u'мягкий знак [ˈmʲæxʲkʲɪj znak]', u'/ʲ/', u'silent, slightly palatalizes the preceding consonant (if it is phonologically possible)'),
    (u'Э', u'э', u'э [ɛ]', u'/e/', u'met'),
    (u'Ю', u'ю', u'ю [ju]', u'/ju/ or /ʲu/', u'use'),
    (u'Я', u'я', u'я [ja]', u'/ja/ or /ʲa/', u'yard'),
)
