# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/cytu/usr/src/py/ananda/designer/wdg_a.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wdg_a(object):
    def setupUi(self, wdg_a):
        wdg_a.setObjectName("wdg_a")
        wdg_a.resize(600, 80)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(wdg_a.sizePolicy().hasHeightForWidth())
        wdg_a.setSizePolicy(sizePolicy)
        wdg_a.setMaximumSize(QtCore.QSize(600, 80))
        self.gridLayout = QtWidgets.QGridLayout(wdg_a)
        self.gridLayout.setContentsMargins(2, 2, 2, 2)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.vlo = QtWidgets.QVBoxLayout()
        self.vlo.setSpacing(0)
        self.vlo.setObjectName("vlo")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_play = QtWidgets.QPushButton(wdg_a)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_play.sizePolicy().hasHeightForWidth())
        self.btn_play.setSizePolicy(sizePolicy)
        self.btn_play.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_play.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_play.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/res/img/media_playback_start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_play.setIcon(icon)
        self.btn_play.setIconSize(QtCore.QSize(24, 24))
        self.btn_play.setAutoDefault(False)
        self.btn_play.setDefault(False)
        self.btn_play.setFlat(True)
        self.btn_play.setObjectName("btn_play")
        self.horizontalLayout.addWidget(self.btn_play)
        self.btn_stop = QtWidgets.QPushButton(wdg_a)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_stop.sizePolicy().hasHeightForWidth())
        self.btn_stop.setSizePolicy(sizePolicy)
        self.btn_stop.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_stop.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_stop.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/res/img/media_playback_stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_stop.setIcon(icon1)
        self.btn_stop.setIconSize(QtCore.QSize(24, 24))
        self.btn_stop.setFlat(True)
        self.btn_stop.setObjectName("btn_stop")
        self.horizontalLayout.addWidget(self.btn_stop)
        self.btn_rec = QtWidgets.QPushButton(wdg_a)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_rec.sizePolicy().hasHeightForWidth())
        self.btn_rec.setSizePolicy(sizePolicy)
        self.btn_rec.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_rec.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_rec.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/res/img/media_record.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_rec.setIcon(icon2)
        self.btn_rec.setIconSize(QtCore.QSize(24, 24))
        self.btn_rec.setCheckable(True)
        self.btn_rec.setFlat(True)
        self.btn_rec.setObjectName("btn_rec")
        self.horizontalLayout.addWidget(self.btn_rec)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lbl_s = QtWidgets.QLabel(wdg_a)
        self.lbl_s.setLineWidth(0)
        self.lbl_s.setText("")
        self.lbl_s.setScaledContents(True)
        self.lbl_s.setObjectName("lbl_s")
        self.horizontalLayout.addWidget(self.lbl_s)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.lbl_t = QtWidgets.QLabel(wdg_a)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_t.sizePolicy().hasHeightForWidth())
        self.lbl_t.setSizePolicy(sizePolicy)
        self.lbl_t.setObjectName("lbl_t")
        self.horizontalLayout.addWidget(self.lbl_t)
        self.vlo.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.sld = QtWidgets.QSlider(wdg_a)
        self.sld.setOrientation(QtCore.Qt.Horizontal)
        self.sld.setObjectName("sld")
        self.horizontalLayout_2.addWidget(self.sld)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.btn_file = QtWidgets.QPushButton(wdg_a)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/res/img/document_save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_file.setIcon(icon3)
        self.btn_file.setObjectName("btn_file")
        self.horizontalLayout_2.addWidget(self.btn_file)
        self.vlo.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.vlo)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(wdg_a)
        QtCore.QMetaObject.connectSlotsByName(wdg_a)

    def retranslateUi(self, wdg_a):
        _translate = QtCore.QCoreApplication.translate
        wdg_a.setWindowTitle(_translate("wdg_a", "Form"))
        self.lbl_t.setText(_translate("wdg_a", "00:00:00"))
        self.btn_file.setText(_translate("wdg_a", "load"))
from . import ananda_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    wdg_a = QtWidgets.QWidget()
    ui = Ui_wdg_a()
    ui.setupUi(wdg_a)
    wdg_a.show()
    sys.exit(app.exec_())
