# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/cytu/usr/src/py/ananda/designer/wdg_tm.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wdg_tm(object):
    def setupUi(self, wdg_tm):
        wdg_tm.setObjectName("wdg_tm")
        wdg_tm.resize(260, 85)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(wdg_tm.sizePolicy().hasHeightForWidth())
        wdg_tm.setSizePolicy(sizePolicy)
        wdg_tm.setMinimumSize(QtCore.QSize(260, 85))
        wdg_tm.setMaximumSize(QtCore.QSize(260, 85))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(14)
        wdg_tm.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/res/img/alarmclock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        wdg_tm.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(wdg_tm)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setContentsMargins(2, 2, 2, 2)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.vlo = QtWidgets.QVBoxLayout()
        self.vlo.setSpacing(0)
        self.vlo.setObjectName("vlo")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_play = QtWidgets.QPushButton(wdg_tm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_play.sizePolicy().hasHeightForWidth())
        self.btn_play.setSizePolicy(sizePolicy)
        self.btn_play.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_play.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_play.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/res/img/media_playback_start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_play.setIcon(icon1)
        self.btn_play.setIconSize(QtCore.QSize(24, 24))
        self.btn_play.setAutoDefault(False)
        self.btn_play.setDefault(False)
        self.btn_play.setFlat(True)
        self.btn_play.setObjectName("btn_play")
        self.horizontalLayout.addWidget(self.btn_play)
        self.btn_stop = QtWidgets.QPushButton(wdg_tm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_stop.sizePolicy().hasHeightForWidth())
        self.btn_stop.setSizePolicy(sizePolicy)
        self.btn_stop.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_stop.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_stop.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/res/img/media_playback_stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_stop.setIcon(icon2)
        self.btn_stop.setIconSize(QtCore.QSize(24, 24))
        self.btn_stop.setFlat(True)
        self.btn_stop.setObjectName("btn_stop")
        self.horizontalLayout.addWidget(self.btn_stop)
        self.lbl = QtWidgets.QLabel(wdg_tm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl.sizePolicy().hasHeightForWidth())
        self.lbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(14)
        self.lbl.setFont(font)
        self.lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl.setObjectName("lbl")
        self.horizontalLayout.addWidget(self.lbl)
        self.vlo.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cbo = QtWidgets.QComboBox(wdg_tm)
        self.cbo.setObjectName("cbo")
        self.horizontalLayout_2.addWidget(self.cbo)
        self.ted = QtWidgets.QTimeEdit(wdg_tm)
        self.ted.setAlignment(QtCore.Qt.AlignCenter)
        self.ted.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.ted.setObjectName("ted")
        self.horizontalLayout_2.addWidget(self.ted)
        self.vlo.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.vlo)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(wdg_tm)
        QtCore.QMetaObject.connectSlotsByName(wdg_tm)

    def retranslateUi(self, wdg_tm):
        _translate = QtCore.QCoreApplication.translate
        wdg_tm.setWindowTitle(_translate("wdg_tm", "Alarm"))
        self.lbl.setText(_translate("wdg_tm", "59:59:59"))
        self.ted.setDisplayFormat(_translate("wdg_tm", "hh:mm:ss"))
from . import ananda_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    wdg_tm = QtWidgets.QWidget()
    ui = Ui_wdg_tm()
    ui.setupUi(wdg_tm)
    wdg_tm.show()
    sys.exit(app.exec_())
