# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/cytu/usr/src/py/ananda/designer/win_hrv.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_win_hrv(object):
    def setupUi(self, win_hrv):
        win_hrv.setObjectName("win_hrv")
        win_hrv.setEnabled(True)
        win_hrv.resize(895, 402)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        win_hrv.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/res/img/tex.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        win_hrv.setWindowIcon(icon)
        win_hrv.setStyleSheet("font: 75 10pt \"Microsoft JhengHei\";")
        self.wdg = QtWidgets.QWidget(win_hrv)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wdg.sizePolicy().hasHeightForWidth())
        self.wdg.setSizePolicy(sizePolicy)
        self.wdg.setObjectName("wdg")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.wdg)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        win_hrv.setCentralWidget(self.wdg)
        self.stb = QtWidgets.QStatusBar(win_hrv)
        self.stb.setObjectName("stb")
        win_hrv.setStatusBar(self.stb)
        self.tb = QtWidgets.QToolBar(win_hrv)
        self.tb.setIconSize(QtCore.QSize(16, 16))
        self.tb.setObjectName("tb")
        win_hrv.addToolBar(QtCore.Qt.TopToolBarArea, self.tb)
        self.mnb = QtWidgets.QMenuBar(win_hrv)
        self.mnb.setGeometry(QtCore.QRect(0, 0, 895, 25))
        self.mnb.setObjectName("mnb")
        self.menu_File = QtWidgets.QMenu(self.mnb)
        self.menu_File.setObjectName("menu_File")
        self.menu_View = QtWidgets.QMenu(self.mnb)
        self.menu_View.setObjectName("menu_View")
        self.menuZoom = QtWidgets.QMenu(self.menu_View)
        self.menuZoom.setObjectName("menuZoom")
        self.menu_Go = QtWidgets.QMenu(self.mnb)
        self.menu_Go.setObjectName("menu_Go")
        self.menuSetti_ngs = QtWidgets.QMenu(self.mnb)
        self.menuSetti_ngs.setObjectName("menuSetti_ngs")
        win_hrv.setMenuBar(self.mnb)
        self.act_fst = QtWidgets.QAction(win_hrv)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/res/img/start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_fst.setIcon(icon1)
        self.act_fst.setObjectName("act_fst")
        self.act_last = QtWidgets.QAction(win_hrv)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/res/img/finish.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_last.setIcon(icon2)
        self.act_last.setObjectName("act_last")
        self.act_prev = QtWidgets.QAction(win_hrv)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/res/img/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_prev.setIcon(icon3)
        self.act_prev.setObjectName("act_prev")
        self.act_next = QtWidgets.QAction(win_hrv)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/res/img/forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_next.setIcon(icon4)
        self.act_next.setObjectName("act_next")
        self.act_fwd = QtWidgets.QAction(win_hrv)
        self.act_fwd.setObjectName("act_fwd")
        self.act_bwd = QtWidgets.QAction(win_hrv)
        self.act_bwd.setObjectName("act_bwd")
        self.act_z_in = QtWidgets.QAction(win_hrv)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/res/img/zoom_in.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_z_in.setIcon(icon5)
        self.act_z_in.setObjectName("act_z_in")
        self.act_z_out = QtWidgets.QAction(win_hrv)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/res/img/zoom_out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_z_out.setIcon(icon6)
        self.act_z_out.setObjectName("act_z_out")
        self.act_best = QtWidgets.QAction(win_hrv)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/res/img/zoom_fit_best.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_best.setIcon(icon7)
        self.act_best.setObjectName("act_best")
        self.act_full = QtWidgets.QAction(win_hrv)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/res/img/window_fullscreen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_full.setIcon(icon8)
        self.act_full.setObjectName("act_full")
        self.act_quit = QtWidgets.QAction(win_hrv)
        self.act_quit.setObjectName("act_quit")
        self.act_tab_next = QtWidgets.QAction(win_hrv)
        self.act_tab_next.setObjectName("act_tab_next")
        self.act_tab_prev = QtWidgets.QAction(win_hrv)
        self.act_tab_prev.setObjectName("act_tab_prev")
        self.act_open_new = QtWidgets.QAction(win_hrv)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/res/img/tab_new_background.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_open_new.setIcon(icon9)
        self.act_open_new.setObjectName("act_open_new")
        self.act_tab_close = QtWidgets.QAction(win_hrv)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/res/img/tab_close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_tab_close.setIcon(icon10)
        self.act_tab_close.setObjectName("act_tab_close")
        self.act_open = QtWidgets.QAction(win_hrv)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/res/img/tab_new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_open.setIcon(icon11)
        self.act_open.setObjectName("act_open")
        self.act_show_tb = QtWidgets.QAction(win_hrv)
        self.act_show_tb.setCheckable(True)
        self.act_show_tb.setObjectName("act_show_tb")
        self.act_show_stb = QtWidgets.QAction(win_hrv)
        self.act_show_stb.setCheckable(True)
        self.act_show_stb.setObjectName("act_show_stb")
        self.act_show_sdb = QtWidgets.QAction(win_hrv)
        self.act_show_sdb.setCheckable(True)
        self.act_show_sdb.setObjectName("act_show_sdb")
        self.act_show_mnb = QtWidgets.QAction(win_hrv)
        self.act_show_mnb.setCheckable(True)
        self.act_show_mnb.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.act_show_mnb.setObjectName("act_show_mnb")
        self.act_tab_close_all = QtWidgets.QAction(win_hrv)
        self.act_tab_close_all.setObjectName("act_tab_close_all")
        self.act_save = QtWidgets.QAction(win_hrv)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/res/img/document_save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_save.setIcon(icon12)
        self.act_save.setObjectName("act_save")
        self.tb.addSeparator()
        self.tb.addAction(self.act_fst)
        self.tb.addAction(self.act_prev)
        self.tb.addAction(self.act_next)
        self.tb.addAction(self.act_last)
        self.tb.addSeparator()
        self.tb.addAction(self.act_z_in)
        self.tb.addAction(self.act_z_out)
        self.tb.addAction(self.act_best)
        self.tb.addSeparator()
        self.menu_File.addAction(self.act_open)
        self.menu_File.addAction(self.act_open_new)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.act_tab_close)
        self.menu_File.addAction(self.act_tab_close_all)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.act_save)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.act_quit)
        self.menuZoom.addAction(self.act_z_in)
        self.menuZoom.addAction(self.act_z_out)
        self.menu_View.addAction(self.menuZoom.menuAction())
        self.menu_View.addAction(self.act_full)
        self.menu_Go.addAction(self.act_fst)
        self.menu_Go.addAction(self.act_last)
        self.menu_Go.addAction(self.act_prev)
        self.menu_Go.addAction(self.act_next)
        self.menu_Go.addSeparator()
        self.menu_Go.addAction(self.act_fwd)
        self.menu_Go.addAction(self.act_bwd)
        self.menu_Go.addSeparator()
        self.menuSetti_ngs.addAction(self.act_show_mnb)
        self.menuSetti_ngs.addAction(self.act_show_sdb)
        self.menuSetti_ngs.addAction(self.act_show_tb)
        self.menuSetti_ngs.addAction(self.act_show_stb)
        self.mnb.addAction(self.menu_File.menuAction())
        self.mnb.addAction(self.menu_View.menuAction())
        self.mnb.addAction(self.menu_Go.menuAction())
        self.mnb.addAction(self.menuSetti_ngs.menuAction())

        self.retranslateUi(win_hrv)
        QtCore.QMetaObject.connectSlotsByName(win_hrv)

    def retranslateUi(self, win_hrv):
        _translate = QtCore.QCoreApplication.translate
        win_hrv.setWindowTitle(_translate("win_hrv", "Ebook Harvester"))
        self.tb.setWindowTitle(_translate("win_hrv", "toolBar"))
        self.menu_File.setTitle(_translate("win_hrv", "&File"))
        self.menu_View.setTitle(_translate("win_hrv", "&View"))
        self.menuZoom.setTitle(_translate("win_hrv", "Zoom"))
        self.menu_Go.setTitle(_translate("win_hrv", "&Go"))
        self.menuSetti_ngs.setTitle(_translate("win_hrv", "Setti&ngs"))
        self.act_fst.setText(_translate("win_hrv", "&First Page"))
        self.act_fst.setShortcut(_translate("win_hrv", "Home"))
        self.act_last.setText(_translate("win_hrv", "&Last Page"))
        self.act_last.setShortcut(_translate("win_hrv", "End"))
        self.act_prev.setText(_translate("win_hrv", "&Previous Page"))
        self.act_prev.setShortcut(_translate("win_hrv", "PgUp"))
        self.act_next.setText(_translate("win_hrv", "&Next Page"))
        self.act_next.setShortcut(_translate("win_hrv", "PgDown"))
        self.act_fwd.setText(_translate("win_hrv", "For&ward"))
        self.act_fwd.setShortcut(_translate("win_hrv", "Alt+Right"))
        self.act_bwd.setText(_translate("win_hrv", "&Backward"))
        self.act_bwd.setShortcut(_translate("win_hrv", "Alt+Left"))
        self.act_z_in.setText(_translate("win_hrv", "Zoom &In"))
        self.act_z_in.setShortcut(_translate("win_hrv", "Ctrl+="))
        self.act_z_out.setText(_translate("win_hrv", "Zoom O&ut"))
        self.act_z_out.setShortcut(_translate("win_hrv", "Ctrl+-"))
        self.act_best.setText(_translate("win_hrv", "Best"))
        self.act_best.setToolTip(_translate("win_hrv", "Best"))
        self.act_best.setShortcut(_translate("win_hrv", "Ctrl+3"))
        self.act_full.setText(_translate("win_hrv", "F&ull Screen"))
        self.act_full.setShortcut(_translate("win_hrv", "F11"))
        self.act_quit.setText(_translate("win_hrv", "&Quit"))
        self.act_quit.setShortcut(_translate("win_hrv", "Ctrl+Q"))
        self.act_tab_next.setText(_translate("win_hrv", "Next Tab"))
        self.act_tab_next.setShortcut(_translate("win_hrv", "Ctrl+Tab"))
        self.act_tab_prev.setText(_translate("win_hrv", "Previous Tab"))
        self.act_tab_prev.setShortcut(_translate("win_hrv", "Ctrl+Shift+Backtab"))
        self.act_open_new.setText(_translate("win_hrv", "Open as New &Tab"))
        self.act_open_new.setToolTip(_translate("win_hrv", "Open as New Tab"))
        self.act_open_new.setShortcut(_translate("win_hrv", "Ctrl+T"))
        self.act_tab_close.setText(_translate("win_hrv", "&Close Tab"))
        self.act_tab_close.setShortcut(_translate("win_hrv", "Ctrl+W"))
        self.act_open.setText(_translate("win_hrv", "&Open"))
        self.act_open.setShortcut(_translate("win_hrv", "Ctrl+O"))
        self.act_show_tb.setText(_translate("win_hrv", "&Toolbar"))
        self.act_show_tb.setToolTip(_translate("win_hrv", "Show Toolbar"))
        self.act_show_tb.setShortcut(_translate("win_hrv", "F10"))
        self.act_show_stb.setText(_translate("win_hrv", "Stat&usbar"))
        self.act_show_stb.setToolTip(_translate("win_hrv", "Show Statusbar"))
        self.act_show_stb.setShortcut(_translate("win_hrv", "Ctrl+F9"))
        self.act_show_sdb.setText(_translate("win_hrv", "&Sidebar"))
        self.act_show_sdb.setToolTip(_translate("win_hrv", "Show Sidebar"))
        self.act_show_sdb.setShortcut(_translate("win_hrv", "F9"))
        self.act_show_mnb.setText(_translate("win_hrv", "Men&ubar"))
        self.act_show_mnb.setToolTip(_translate("win_hrv", "Show Menubar"))
        self.act_show_mnb.setShortcut(_translate("win_hrv", "F8"))
        self.act_tab_close_all.setText(_translate("win_hrv", "Close &All Tabs"))
        self.act_tab_close_all.setShortcut(_translate("win_hrv", "Ctrl+Shift+W"))
        self.act_save.setText(_translate("win_hrv", "&Save"))
        self.act_save.setShortcut(_translate("win_hrv", "F2"))
from . import ananda_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    win_hrv = QtWidgets.QMainWindow()
    ui = Ui_win_hrv()
    ui.setupUi(win_hrv)
    win_hrv.show()
    sys.exit(app.exec_())
